name: Test
on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize

permissions: {}

jobs:
  renovate-config-validator:
    # This job is based on https://github.com/renovatebot/github-action/blob/700f3b59b9d0fc6dffce45b564ee1f58869973b1/.github/workflows/build.yml#L132-L148
    name: Validate Renovate config
    runs-on: ubuntu-latest
    permissions:
      contents: read
    timeout-minutes: 10
    container:
      image: ghcr.io/renovatebot/renovate:44.5.3@sha256:0de2072bc4c87e1744158adfb8ccd9f49c5bd2da5a0c14bc4b0c90a7cdaab54f
      # github hosted runners are running as `1001:127` (ubuntu:docker)
      options: -u 1001:0 --group-add 1000 --group-add 12021 --group-add 127

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          show-progress: false
          persist-credentials: false

      - name: Validate Renovate configuration
        run: |
          renovate-config-validator renovate.json
